version: "3"

services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Pass123
      MYSQL_DATABASE: StudentDb
      MYSQL_USER: root
    volumes:
      - /data/mysql
    ports:
      - "3306:3306"
    networks:
      - bootapp

  appservice:
    image: sb-app
    networks:
      - bootapp
    depends_on:
      - mysqldb
    volumes:
      - /data/springboot-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/StudentDb
      SPRING_DATASOURCE_PASSWORD: Pass123

    ports:
      - "9090:9090"
networks:
  bootapp: 


